# An introduction to Numpy
###### **11.01.2022**

In [3]:
import numpy as np

a1= np.array([1, 2, 3])
a1
a1.ndim
a1.shape

(3,)

In [4]:
a2= np.array([[1, 2, 3], [3, 4, 5]])
a2
a2.ndim
a2.shape

(2, 3)

In [13]:
a4= np.array([[1, 2, 3], [3, 4, 5], [3, 4, 5], [3, 4, 5]])
print(a4)
a4.ndim
a4.shape

[[1 2 3]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


(4, 3)

The *ndim* command gives information about the dimensions of the array. If an array can be defined by an only position in space (list), the dimension is 1 and its shape may be defined by an only entry in the *shape* command. In the other hand, if the array can be defined by two coordinates (as any matrix that has a set of rows and a set of columns). Then the ndim will be 2, and the shape will give information of the **number of rows | axis=0** and the **number of columns | axis =1**.

In [12]:
a5 = np.arange(0, 15)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

if we wanted to create an array with a sequence of numbers we could use the function arange() as shown in the first line. In the other hand, if we want to create an arrange in a sequence of numbers in step of size 2, the secon line must be checked.




In [7]:
a7= np.linspace(0, 100, 3)
a7

array([  0.,  50., 100.])

In the case in wich we want to specify the number of points needed in the spacing, but we dont know the exact size of the steps we use linspace. The points will be generated so that they are equally spaced as in the example above. Additionally, we can exclude the last point in the linspace using the following command.

In [8]:
np.linspace(0, 100, 3, endpoint=False)

array([ 0.        , 33.33333333, 66.66666667])

In [9]:
x=np.array(11)
x

array(11)

In [10]:
x=np.array(11)
x.shape

()

In [11]:
x=np.array([1,"2",3])
x.dtype

dtype('<U11')